exclude: [vendor]
enforce_ssl: txuritan.github.io

permalink: /:categories/:title/
github_url: https://github.com/Txuritan
tumblr_url: http://txuritan.tumblr.com/
twitter_url: https://twitter.com/TxuritanS

# WIKI

# Wiki config
wiki-name: "TKI-101 Wiki"
wiki-custom: false
kramdown:
  parse_block_html: true

# Footer Config
footer-year: "2015"
footer-comp: "SnowKAT"
footer-url: ""

footer-bottom2: "Terms Of Survice"
footer-bottom2-url: "tos/"

footer-bottom3: "Privacy"
footer-bottom3-url: "privacy/"

footer-col1-num1-text: "About Us"
footer-col1-num1-url: "about/"
footer-col1-num2-text: "Blog"
footer-col1-num2-url: "blog/"

footer-col2-num1-text: "Contact Us"
footer-col2-num1-url: "contact/"
footer-col2-num2-text: "Contribute"
footer-col2-num2-url: "contribute/"

footer-col3-num1-text: "Community"
footer-col3-num1-url: "community/"
footer-col3-num2-text: "Sitemap"
footer-col3-num2-url: "sitemap/"

footer-col4-num1-text: "Help"
footer-col4-num1-url: "help/"
footer-col4-num2-text: "API"
footer-col4-num2-url: "api/"
