if (document.URL.indexOf("index.html") >= 0) {
    document.getElementById('home').className += 'active'
} else if (document.URL.indexOf("downloads.html") >= 0) {
    document.getElementById('downloads').className += 'active'
} else if (document.URL.indexOf("minecraft-patch.html") >= 0) {
    document.getElementById('minecraft-patch').className += 'active'
} else if (document.URL.indexOf("minecraft-wither-realms.html") >= 0) {
    document.getElementById('minecraft-wither-realms').className += 'active'
} else if (document.URL.indexOf("minecraft-legendary-worlds.html") >= 0) {
    document.getElementById('minecraft-legendary-worlds').className += 'active'
} else if (document.URL.indexOf("minecraft-potatocraft.html") >= 0) {
    document.getElementById('minecraft-potatocraft').className += 'active'
} else if (document.URL.indexOf("skyrim-patch.html") >= 0) {
    document.getElementById('skyrim-patch').className += 'active'
} else if (document.URL.indexOf("skyrim-skyrim-modpack.html") >= 0) {
    document.getElementById('skyrim-skyrim-modpack').className += 'active'
} else if (document.URL.indexOf("skyrim-txuritans-skyrim-modpack.html") >= 0) {
    document.getElementById('skyrim-txuritans-skyrim-modpack').className += 'active'
} else if (document.URL.indexOf("alla-and-taeh.html") >= 0) {
    document.getElementById('alla-and-taeh').className += 'active'
}